(when (require 'multi-web-mode nil t)
  (setq mweb-default-major-mode 'nxml-mode)
  (setq mweb-tags '((php-mode "<\\?php\\|<\\? \\|<\\?=" "\\?>")
                    (js2-mode "<script +\\(type=\"text/javascript\"\\|language=\"javascript\"\\)[^>]*>" "</script>")
                    (css-mode "<style +type=\"text/css\"[^>]*>" "</style>")))
  (setq mweb-filename-extensions '("php" "htm" "html" "ctp" "phtml" "php4" "php5"))
  (multi-web-global-mode 1)

  (add-hook 'nxml-mode-hook (lambda ()
                              (add-to-list (make-local-variable 'yas-extra-modes) 'html-mode))))
